import React from 'react';
import { PencilSimple } from '@phosphor-icons/react';
import { formatRelativeTime } from '@/lib/time';

interface IterationRowHeaderProps {
  title: string;
  direction: string | null;
  sourceName: string | null;
  createdAt: string;
  iterationIndex: number;
  /** When true, renders a small "Edited" pill next to the title — for jobs
   *  generated by editing a previous iteration (parent_job_id present). */
  isEdited?: boolean;
}

export const IterationRowHeader: React.FC<IterationRowHeaderProps> = ({
  title,
  direction,
  sourceName,
  createdAt,
  iterationIndex,
  isEdited = false,
}) => {
  const trimmedDirection = direction?.trim() || null;
  const trimmedSource = sourceName?.trim() || null;
  const relativeTime = formatRelativeTime(createdAt);

  const metaPill = (() => {
    if (trimmedSource && relativeTime) return `${trimmedSource} · ${relativeTime}`;
    if (trimmedSource) return trimmedSource;
    return relativeTime;
  })();

  return (
    <div className="flex flex-col gap-0.5 min-w-0 flex-1 overflow-hidden">
      <div className="flex items-baseline min-w-0 gap-1.5">
        <span className="text-xs font-medium text-stone-400 tabular-nums flex-shrink-0">
          #{iterationIndex}
        </span>
        <span className="text-sm font-medium text-stone-800 truncate">{title}</span>
        {isEdited && (
          <span className="inline-flex items-center gap-0.5 text-[10px] text-primary bg-primary/10 px-1 py-0.5 rounded flex-shrink-0">
            <PencilSimple size={9} />
            Edited
          </span>
        )}
      </div>
      {trimmedDirection && (
        <p
          className="text-xs text-stone-500 line-clamp-1"
          title={trimmedDirection}
        >
          {trimmedDirection}
        </p>
      )}
      <p className="text-[11px] text-stone-500 truncate">{metaPill}</p>
    </div>
  );
};
